### ISSUE TITLE
Fails to compile with GHC 9.2.1

### ISSUE THREAD

**Issue by dunrix** [rblaze/haskell-dbus#54]
> [13 of 14] Compiling DBus.Generation  ( lib/DBus/Generation.hs, dist/build/DBus/Generation.o, dist/build/DBus/Generation.dyn_o )
> 
> lib/DBus/Generation.hs:151:24: error:
>     • Couldn't match expected type ‘Pat’
>                   with actual type ‘[Pat] -> Pat’
>     • Probable cause: ‘ConP’ is applied to too few arguments
>       In the expression: ConP 'Just [VarP name]
>       In an equation for ‘makeJustPattern’:
>           makeJustPattern name = ConP 'Just [VarP name]
>     |
> 151 | makeJustPattern name = ConP 'Just [VarP name]
>     |                        ^^^^^^^^^^^^^^^^^^^^^^
> 
> lib/DBus/Generation.hs:151:36: error:
>     • Couldn't match expected type ‘Type’ with actual type ‘Pat’
>     • In the expression: VarP name
>       In the second argument of ‘ConP’, namely ‘[VarP name]’
>       In the expression: ConP 'Just [VarP name]
>     |
> 151 | makeJustPattern name = ConP 'Just [VarP name]
>     |                                    ^^^^^^^^^
> cabal: Failed to build dbus-1.2.21
